In [13]:
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
# Reference the file where the CSV is located
teamsCsvPath = "Teams.csv"

# Import the data into a Pandas DataFrame
wholeDF = pd.read_csv(teamsCsvPath)
wholeDF.head()

,yearID,lgID,teamID,franchID,divID,Rank,G,Ghome,W,L,...,DP,FP,name,park,attendance,BPF,PPF,teamIDBR,teamIDlahman45,teamIDretro
0,1871,NaN,BS1,BNA,NaN,3,31,NaN,20,10,...,24,0.834,Boston Red Stockings,South End Grounds I,NaN,103,98,BOS,BS1,BS1
1,1871,NaN,CH1,CNA,NaN,2,28,NaN,19,9,...,16,0.829,Chicago White Stockings,Union Base-Ball Grounds,NaN,104,102,CHI,CH1,CH1
2,1871,NaN,CL1,CFC,NaN,8,29,NaN,10,19,...,15,0.818,Cleveland Forest Citys,National Association Grounds,NaN,96,100,CLE,CL1,CL1
3,1871,NaN,FW1,KEK,NaN,7,19,NaN,7,12,...,8,0.803,Fort Wayne Kekiongas,Hamilton Field,NaN,101,107,KEK,FW1,FW1
4,1871,NaN,NY2,NNA,NaN,5,33,NaN,16,17,...,14,0.840,New York Mutuals,Union Grounds (Brooklyn),NaN,90,88,NYU,NY2,NY2

In [5]:
teamHR = wholeDF[["franchID", "HR"]]
teamHR.head()

  franchID  HR
0      BNA   3
1      CNA  10
2      CFC   7
3      KEK   2
4      NNA   1

In [6]:
cleanerDF = wholeDF.drop(wholeDF[wholeDF.yearID < 1970].index)
cleanerDF.head()

,yearID,lgID,teamID,franchID,divID,Rank,G,Ghome,W,L,...,DP,FP,name,park,attendance,BPF,PPF,teamIDBR,teamIDlahman45,teamIDretro
1541,1970,NL,ATL,ATL,W,5,162,81.0,76,86,...,118,0.977,Atlanta Braves,Atlanta-Fulton County Stadium,1078848.0,106,106,ATL,ATL,ATL
1542,1970,AL,BAL,BAL,E,1,162,81.0,108,54,...,148,0.981,Baltimore Orioles,Memorial Stadium,1057069.0,101,98,BAL,BAL,BAL
1543,1970,AL,BOS,BOS,E,3,162,81.0,87,75,...,131,0.974,Boston Red Sox,Fenway Park II,1595278.0,108,107,BOS,BOS,BOS
1544,1970,AL,CAL,ANA,W,3,162,81.0,86,76,...,169,0.980,California Angels,Anaheim Stadium,1077741.0,96,97,CAL,CAL,CAL
1545,1970,AL,CHA,CHW,W,6,162,84.0,56,106,...,187,0.975,Chicago White Sox,Comiskey Park,495355.0,101,102,CHW,CHA,CHA

In [7]:
##cleanestDF = cleanerDF.drop(cleanerDF.teamIDretro, cleanerDF.attendance)
##cleanestDF

columns = ['park',
           'attendance',
           'BPF',
           'PPF',
           'teamIDBR',
           'teamIDlahman45',
           'teamIDretro',
           'IPouts',
           'HA',
           'HRA',
           'BBA',
           'SOA',
           'DP',
           'FP',
           'CS', 
           'HBP', 
           'SF', 
           'RA',
           'SHO',
           'DivWin',
           'WCWin',
           'lgID',
           'teamID',
           'DivWin',
           'WCWin',
           'LgWin',
           'WSWin',
           'divID',
           'name',
           'franchID'
          ]

cleanerDF.drop(columns, inplace=True, axis=1)
cleanerDF.head()

,yearID,Rank,G,Ghome,W,L,R,AB,H,2B,3B,HR,BB,SO,SB,ER,ERA,CG,SV,E
1541,1970,5,162,81.0,76,86,736,5546,1495,215,24,160,522.0,736.0,58.0,688,4.33,45,24,141
1542,1970,1,162,81.0,108,54,792,5545,1424,213,25,179,717.0,952.0,84.0,517,3.15,60,31,117
1543,1970,3,162,81.0,87,75,786,5535,1450,252,28,203,594.0,855.0,50.0,622,3.87,38,44,156
1544,1970,3,162,81.0,86,76,631,5532,1391,197,40,114,447.0,922.0,69.0,566,3.48,21,49,127
1545,1970,6,162,84.0,56,106,633,5514,1394,192,20,123,477.0,872.0,53.0,722,4.54,20,30,165

In [8]:
# This lets me know that 2006 is about the last year in the 75% range for the training dataset
n = 76
cleanerDF.head(int(len(cleanerDF)*(n/100)))

,yearID,Rank,G,Ghome,W,L,R,AB,H,2B,3B,HR,BB,SO,SB,ER,ERA,CG,SV,E
1541,1970,5,162,81.0,76,86,736,5546,1495,215,24,160,522.0,736.0,58.0,688,4.33,45,24,141
1542,1970,1,162,81.0,108,54,792,5545,1424,213,25,179,717.0,952.0,84.0,517,3.15,60,31,117
1543,1970,3,162,81.0,87,75,786,5535,1450,252,28,203,594.0,855.0,50.0,622,3.87,38,44,156
1544,1970,3,162,81.0,86,76,631,5532,1391,197,40,114,447.0,922.0,69.0,566,3.48,21,49,127
1545,1970,6,162,84.0,56,106,633,5514,1394,192,20,123,477.0,872.0,53.0,722,4.54,20,30,165
1546,1970,2,162,80.0,84,78,806,5491,1424,228,44,179,607.0,844.0,39.0,599,3.76,59,25,137
1547,1970,1,162,81.0,102,60,775,5540,1498,253,45,191,547.0,984.0,115.0,592,3.69,32,60,151
1548,1970,5,162,81.0,76,86,649,5463,1358,197,23,183,503.0,909.0,25.0,630,3.91,34,35,133
1549,1970,4,162,81.0,79,83,666,5377,1282,207,38,148,656.0,825.0,29.0,658,4.09,33,39,133
1550,1970,4,162,81.0,79,83,744,5574,1446,250,47,129,598.0,911.0,114.0,685,4.23,36,35,140
1551,1970,4,162,79.0,65,97,611,5503,1341,202,41,97,514.0,958.0,97.0,615,3.78,30,25,152
1552,1970,2,161,81.0,87,74,749,5606,1515,233,67,87,541.0,841.0,138.0,619,3.82,37,42,135
1553,1970,1,162,81.0,98,64,744,5483,1438,230,41,153,501.0,905.0,57.0,520,3.23,26,58,123
1554,1970,4,163,81.0,65,97,613,5395,1305,202,24,126,592.0,985.0,91.0,676,4.21,31,27,136
1555,1970,6,162,80.0,73,89,687,5411,1284,211,35,136,659.0,972.0,65.0,720,4.50,29,32,141
1556,1970,2,163,81.0,93,69,680,5492,1381,208,41,111,588.0,808.0,105.0,530,3.24,36,49,130
1557,1970,3,162,82.0,83,79,695,5443,1358,211,42,120,684.0,1062.0,118.0,559,3.45,47,32,124
1558,1970,2,162,81.0,89,73,678,5376,1338,208,24,171,584.0,977.0,131.0,529,3.30,33,40,141
1559,1970,5,161,80.0,73,88,594,5456,1299,224,58,101,519.0,1066.0,72.0,677,4.17,24,36,114
1560,1970,1,162,82.0,89,73,729,5637,1522,235,70,130,444.0,871.0,66.0,597,3.70,36,43,137
1561,1970,6,162,81.0,63,99,681,5494,1353,208,36,172,500.0,1164.0,60.0,697,4.36,24,32,158
1562,1970,3,162,81.0,86,76,831,5578,1460,257,35,165,729.0,1005.0,83.0,729,4.50,50,30,170
1563,1970,4,162,81.0,76,86,744,5689,1497,218,51,113,569.0,961.0,117.0,665,4.06,51,20,150
1564,1970,6,162,81.0,70,92,626,5460,1302,184,28,138,635.0,989.0,72.0,615,3.80,20,40,116
1565,1971,3,162,82.0,82,80,643,5575,1434,192,30,153,434.0,747.0,57.0,614,3.75,40,31,146
1566,1971,1,158,77.0,101,57,742,5303,1382,207,25,158,672.0,844.0,66.0,470,2.99,71,22,112
1567,1971,3,162,80.0,85,77,691,5401,1360,246,28,161,552.0,871.0,51.0,610,3.80,44,35,116
1568,1971,4,162,81.0,76,86,511,5495,1271,213,18,96,441.0,827.0,72.0,510,3.10,39,32,131
1569,1971,3,162,81.0,79,83,617,5382,1346,185,30,138,562.0,870.0,83.0,503,3.12,46,32,160
1570,1971,3,162,81.0,83,79,637,5438,1401,202,34,128,527.0,772.0,44.0,579,3.61,75,13,126
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2517,2006,5,162,81.0,62,100,757,5589,1515,335,37,124,474.0,1040.0,65.0,896,5.65,3,35,98
2518,2006,2,162,81.0,89,73,766,5609,1539,309,29,159,486.0,914.0,148.0,652,4.04,5,50,124
2519,2006,2,162,81.0,88,74,820,5628,1552,307,58,153,601.0,959.0,128.0,686,4.23,1,40,115
2520,2006,4,162,81.0,75,87,730,5433,1400,301,20,180,502.0,1233.0,71.0,763,4.82,7,43,117
2521,2006,1,162,81.0,96,66,801,5602,1608,275,34,143,490.0,872.0,101.0,632,3.95,1,40,84
2522,2006,1,162,81.0,97,65,930,5651,1608,327,21,210,649.0,1053.0,139.0,708,4.41,5,43,104
2523,2006,1,162,81.0,97,65,834,5558,1469,323,41,200,547.0,1071.0,146.0,673,4.14,5,43,104
2524,2006,1,162,81.0,93,69,771,5500,1429,266,22,175,650.0,976.0,61.0,679,4.21,5,54,84
2525,2006,2,162,81.0,85,77,865,5687,1518,294,41,216,626.0,1203.0,92.0,747,4.60,4,42,104
2526,2006,5,162,81.0,67,95,691,5558,1462,286,17,141,459.0,1200.0,68.0,720,4.52,2,39,104
2527,2006,1,162,81.0,88,74,731,5576,1465,298,38,161,564.0,1104.0,123.0,629,3.87,4,50,92
2528,2006,4,162,81.0,78,84,756,5670,1540,266,42,172,404.0,974.0,106.0,739,4.60,6,47,88
2529,2006,3,161,81.0,76,85,746,5472,1418,297,52,163,494.0,891.0,58.0,735,4.63,7,37,91
2530,2006,1,161,80.0,83,78,781,5522,1484,292,27,184,531.0,922.0,59.0,721,4.54,6,38,98
2531,2006,5,162,81.0,61,101,689,5474,1395,267,33,190,441.0,1106.0,134.0,782,4.96,3,33,116
2532,2006,3,162,81.0,80,82,835,5659,1571,357,23,183,505.0,1061.0,53.0,731,4.60,3,42,98
2533,2006,2,162,81.0,87,75,809,5596,1591,348,27,199,514.0,906.0,65.0,694,4.37,6,42,99
2534,2006,5,162,81.0,71,91,746,5495,1437,322,22,164,594.0,1156.0,123.0,803,5.03,1,32,131
2535,2007,1,162,81.0,90,72,712,5398,1350,286,40,171,532.0,1111.0,109.0,662,4.13,7,51,106
2536,2007,3,162,81.0,84,78,810,5689,1562,328,27,176,534.0,1149.0,64.0,665,4.11,1,36,107
2537,2007,4,162,81.0,69,93,756,5631,1529,306,30,142,500.0,939.0,144.0,827,5.17,4,30,79
2538,2007,1,162,81.0,96,66,867,5589,1561,352,35,166,689.0,1042.0,96.0,618,3.87,5,45,81
2539,2007,4,162,81.0,72,90,693,5441,1341,249,20,190,532.0,1149.0,78.0,763,4.77,9,42,108
2540,2007,1,162,81.0,85,77,752,5643,1530,340,28,151,500.0,1054.0,86.0,650,4.04,2,39,94
2541,2007,5,162,81.0,72,90,783,5607,1496,293,23,204,536.0,1113.0,97.0,796,4.94,6,34,95
2542,2007,1,162,80.0,96,66,811,5604,1504,305,27,178,590.0,1202.0,72.0,658,4.05,9,49,92
2543,2007,2,163,82.0,90,73,860,5691,1591,313,36,171,622.0,1152.0,100.0,706,4.32,4,39,68
2544,2007,2,162,81.0,88,74,887,5757,1652,352,50,177,474.0,1054.0,103.0,735,4.57,1,44,99
2545,2007,5,162,81.0,71,91,790,5627,1504,340,38,201,521.0,1332.0,105.0,793,4.94,0,40,137
2546,2007,4,162,81.0,73,89,723,5605,1457,293,30,167,547.0,1043.0,65.0,761,4.68,2,38,103

In [9]:
trainingDF = cleanerDF.drop(cleanerDF[cleanerDF.yearID > 2006].index)
testingDF  = cleanerDF.drop(cleanerDF[cleanerDF.yearID < 2007].index)
testingDF.head()

,yearID,Rank,G,Ghome,W,L,R,AB,H,2B,3B,HR,BB,SO,SB,ER,ERA,CG,SV,E
2535,2007,1,162,81.0,90,72,712,5398,1350,286,40,171,532.0,1111.0,109.0,662,4.13,7,51,106
2536,2007,3,162,81.0,84,78,810,5689,1562,328,27,176,534.0,1149.0,64.0,665,4.11,1,36,107
2537,2007,4,162,81.0,69,93,756,5631,1529,306,30,142,500.0,939.0,144.0,827,5.17,4,30,79
2538,2007,1,162,81.0,96,66,867,5589,1561,352,35,166,689.0,1042.0,96.0,618,3.87,5,45,81
2539,2007,4,162,81.0,72,90,693,5441,1341,249,20,190,532.0,1149.0,78.0,763,4.77,9,42,108

In [10]:

maxWin = cleanerDF["W"].max()
maxWin

116

In [15]:
from sklearn.linear_model import LinearRegression

In [19]:
lm = LinearRegression()
lm

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [17]:
# Fit the model to the training data and calculate the scores for the training and testing data

### BEGIN SOLUTION
model.fit(X_train, y_ train)
training_score = model.score(X_train, y_train)
testing_score = model.score(X_test, y_test)

### END SOLUTION 

print(f"Training Score: {training_score}")
print(f"Testing Score: {testing_score}")

SyntaxError: invalid syntax (<ipython-input-17-63a06f928b06>, line 4)

In [20]:
### BEGIN SOLUTION
plt.scatter(lm.predict(X_train), lm.predict(X_train) - y_train, c="blue", label="Training Data")
plt.scatter(lm.predict(X_test), lm.predict(X_test) - y_test, c="orange", label="Testing Data")
plt.legend()
plt.hlines(y=0, xmin=y.min(), xmax=y.max())
plt.title("Residual Plot")
### END SOLUTION

NameError: name 'X_train' is not defined

In [ ]:
import pandas as pd

from sklearn.linear_model import LinearRegression

X=trainingDF['R'].values.reshape(-1, 1)#, 'HR']

y=trainingDF['W'].values.reshape(-1, 1)

X_test=testingDF["R"].values.reshape(-1, 1)#, 'HR']

y_test=testingDF["W"].values.reshape(-1, 1)

lm=LinearRegression()


lm.fit(X,y)

In [ ]:
lm.coef_

In [ ]:
lm.intercept_

In [ ]:
X.shape

In [ ]:
y.shape

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
### BEGIN SOLUTION
###plt.scatter(lm.predict(X_train), lm.predict(X_train) - y_train, c="blue", label="Training Data")
###plt.scatter(lm.predict(X_test), lm.predict(X_test) - y_test, c="orange", label="Testing Data")
###plt.legend()
#plt.hlines(y=0, xmin=y.min(), xmax=y.max())
###plt.title("Residual Plot")
### END SOLUTION

In [ ]:
userInput = lm.predict([[1150]]) 
userInput

In [ ]:
x_min = X.min()
x_max = X.max()

In [ ]:
y_min_actual = y.min()
y_max_actual = y.max()

In [ ]:
y_min = 25.49953363 + 0.07574526 * x_min
y_max = 25.49953363 + 0.07574526 * x_max
print(f"Actual Min Value: {y_min_actual}")
print(f"Calculated Min Value: {y_min}")
print(f"Actual Max Value: {y_max_actual}")
print(f"Calculated Max Value: {y_max}")

In [ ]:
y_min_predicted = lm.predict(x_min)
y_max_predicted = lm.predict(x_max)
print(f"Actual Min Value: {y_min_actual}")
print(f"Predicted Min Value: {y_min_predicted}")
print(f"Actual Max Value: {y_max_actual}")
print(f"Predicted Max Value: {y_max_predicted}")

In [ ]:
plt.scatter(X, y, c='blue', marker='+')
##plt.scatter(userInput, y, c='red')
plt.xlabel("Number of Runs")
plt.ylabel("Number of Wins")
plt.plot([x_min, x_max], [y_min, y_max], c='red')
#plt.scatter(userInput, y, c='red', marker='+')
#userInput

In [ ]:
import pickle

In [ ]:
with open('lm_pickle','wb') as file:
    pickle.dump(model,file)

In [ ]:
# Sperate train and test data
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

# There are three steps to model something with sklearn
# 1. Set up the model
model = LinearRegression()
# 2. Use fit
model.fit(X_train, y_train)
# 3. Check the score
model.score(X_test, y_test)